# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "runtime-extension-maintenance-controller"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/runtime-extension-maintenance-controller"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "*/*.drawio.png",
]
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "crd/machines.yaml",
]
SPDX-FileCopyrightText = "Copyright 2018 The Kubernetes Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "crd/baremetalhosts.yaml",
]
SPDX-FileCopyrightText = "Copyright 2024 The Metal3 Authors"
SPDX-License-Identifier = "Apache-2.0"
